// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g22NpEkpt3JYcyPsqXfiy7
// Component: im0gTx8qZYUz
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: g22NpEkpt3JYcyPsqXfiy7/projectcss
import sty from "./PlasmicCurrentTimeComponent.module.css"; // plasmic-import: im0gTx8qZYUz/css

createPlasmicElementProxy;

export const PlasmicCurrentTimeComponent__VariantProps = new Array();

export const PlasmicCurrentTimeComponent__ArgProps = new Array();

const $$ = {};

function PlasmicCurrentTimeComponent__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const [time, setTime] = React.useState(new Date());

  React.useEffect(() => {
    const interval = setInterval(() => {
      setTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={`${classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__pnCs
        )}`}
      >
        {`${time.toLocaleDateString("en-US", { weekday: "long" })}, ${time.toLocaleDateString()}`}
      </div>
      <div
        className={`w-[180px] ${classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__iTiOs
        )}`}
      >
         {time.toLocaleTimeString()}
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCurrentTimeComponent__ArgProps,
          internalVariantPropNames: PlasmicCurrentTimeComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCurrentTimeComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCurrentTimeComponent";
  } else {
    func.displayName = `PlasmicCurrentTimeComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicCurrentTimeComponent = Object.assign(
  // Top-level PlasmicCurrentTimeComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCurrentTimeComponent
    internalVariantProps: PlasmicCurrentTimeComponent__VariantProps,
    internalArgProps: PlasmicCurrentTimeComponent__ArgProps
  }
);

export default PlasmicCurrentTimeComponent;
/* prettier-ignore-end */
