// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g22NpEkpt3JYcyPsqXfiy7
// Component: B0adBUCTRclN
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TableComponent from "../../TableComponent"; // plasmic-import: -K3huKWfaZz7/component
import PieChartComponent from "../../PieChartComponent"; // plasmic-import: lt9TO1JSwwxD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: g22NpEkpt3JYcyPsqXfiy7/projectcss
import sty from "./PlasmicTablePieChartComponent.module.css"; // plasmic-import: B0adBUCTRclN/css

createPlasmicElementProxy;

export const PlasmicTablePieChartComponent__VariantProps = new Array();

export const PlasmicTablePieChartComponent__ArgProps = new Array("query");

const $$ = {};

function PlasmicTablePieChartComponent__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div style={{ width:"100vw", display: "flex", justifyContent: "space-between",padding:"0 10px" }}>
        <TableComponent
          data-plasmic-name={"tableComponent"}
          data-plasmic-override={overrides.tableComponent}
          className={classNames("__wab_instance", sty.tableComponent)}
          query={$props.query}
        />

        <PieChartComponent
          data-plasmic-name={"pieChartComponent"}
          data-plasmic-override={overrides.pieChartComponent}
          // className={classNames("__wab_instance", sty.pieChartComponent)}
        />
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root", "tableComponent", "pieChartComponent"],
  tableComponent: ["tableComponent"],
  pieChartComponent: ["pieChartComponent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTablePieChartComponent__ArgProps,
          internalVariantPropNames: PlasmicTablePieChartComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTablePieChartComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTablePieChartComponent";
  } else {
    func.displayName = `PlasmicTablePieChartComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicTablePieChartComponent = Object.assign(
  // Top-level PlasmicTablePieChartComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tableComponent: makeNodeComponent("tableComponent"),
    pieChartComponent: makeNodeComponent("pieChartComponent"),
    // Metadata about props expected for PlasmicTablePieChartComponent
    internalVariantProps: PlasmicTablePieChartComponent__VariantProps,
    internalArgProps: PlasmicTablePieChartComponent__ArgProps
  }
);

export default PlasmicTablePieChartComponent;
/* prettier-ignore-end */
